version: '3.8'
services:
  postgresdb:
    image: postgres:15.5-alpine3.18
    restart: always
    container_name: postgresdb
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - ./db_volume:/var/lib/postgresql/data
